# Generated by Django 5.2.18 on 2026-10-09 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('secao', models.CharField(choices=[('artigos', 'Artigos'), ('destaques-github', 'Destaques GitHub'), ('radar-hf', 'Radar Hugging Face')], max_length=32)),
                ('tipo', models.CharField(choices=[('artigo', 'Artigo'), ('lista', 'Lista (curadoria)')], default='artigo', max_length=16)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publicado_em', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('resumo', models.TextField(blank=True, default='')),
                ('corpo', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='content.conteudo')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicado_em', models.DateTimeField()),
                ('retirado_em', models.DateTimeField(blank=True, null=True)),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='content.conteudo')),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicacoes', to='content.versao')),
            ],
            options={
                'ordering': ['-publicado_em'],
            },
        ),
        migrations.AddField(
            model_name='conteudo',
            name='versao_em_edicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='em_edicao_em_conteudos', to='content.versao'),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='versao_publicada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicado_em_conteudos', to='content.versao'),
        ),
        migrations.CreateModel(
            name='Aprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('humano', 'Humano'), ('automatico', 'Automático')], default='humano', max_length=16)),
                ('regras_avaliadas', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('versao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacao', to='content.versao')),
            ],
        ),
    ]
