# Generated by Django 5.2.18 on 2026-10-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='estado',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_revisao', 'Aguardando revisão'), ('aprovado', 'Aprovado'), ('publicado', 'Publicado'), ('publicado_em_edicao', 'Publicado em edição'), ('rejeitado', 'Rejeitado'), ('retirado', 'Retirado')], default='rascunho', max_length=24),
        ),
    ]
