# Generated by Django 5.2.18 on 2026-10-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_conteudo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='versao',
            name='metadados',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
