# Generated by Django 5.2.18 on 2026-10-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_versao_metadados'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='publicacao',
            constraint=models.UniqueConstraint(condition=models.Q(('retirado_em__isnull', True)), fields=('conteudo', 'versao'), name='uniq_publicacao_ativa_conteudo_versao'),
        ),
    ]
