# Generated by Django 5.2.18 on 2026-10-09 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_publicacao_uniq_publicacao_ativa_conteudo_versao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('tipo', models.CharField(default='repositorio', max_length=16)),
                ('dados', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='content.versao')),
            ],
            options={
                'ordering': ['ordem'],
                'constraints': [models.UniqueConstraint(fields=('versao', 'ordem'), name='uniq_item_versao_ordem')],
            },
        ),
    ]
