# Generated by Django 5.2.18 on 2026-10-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('repositorio', 'Repositório'), ('modelo', 'Modelo')], default='repositorio', max_length=16),
        ),
    ]
