# Generated by Django 5.2.18 on 2026-10-09 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('github', 'GitHub'), ('huggingface', 'Hugging Face')], max_length=32)),
                ('nome', models.CharField(max_length=120)),
                ('habilitada', models.BooleanField(default=True)),
                ('credencial_ref', models.CharField(blank=True, default='', max_length=120)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'nome'), name='uniq_fonte_tipo_nome')],
            },
        ),
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('em_andamento', 'Em andamento'), ('ok', 'OK'), ('falhou_parcial', 'Falhou (parcial)'), ('falhou', 'Falhou')], default='em_andamento', max_length=16)),
                ('iniciada_em', models.DateTimeField()),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('erro', models.TextField(blank=True, default='')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coletas', to='sources.fonte')),
            ],
            options={
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroNormalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_externa', models.CharField(max_length=200)),
                ('dados', models.JSONField(default=dict)),
                ('coletado_em', models.DateTimeField()),
                ('coleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='sources.coleta')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='sources.fonte')),
            ],
            options={
                'ordering': ['-coletado_em'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.FloatField(default=0)),
                ('motivo', models.TextField(blank=True, default='')),
                ('selecionado', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to='sources.registronormalizado')),
            ],
            options={
                'ordering': ['-pontuacao'],
            },
        ),
        migrations.AddConstraint(
            model_name='registronormalizado',
            constraint=models.UniqueConstraint(fields=('fonte', 'chave_externa'), name='uniq_registro_fonte_chave'),
        ),
    ]
