# Generated by Django 5.2.18 on 2026-10-09 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_diario', models.DecimalField(decimal_places=6, max_digits=14)),
                ('limite_mensal', models.DecimalField(decimal_places=6, max_digits=14)),
                ('moeda', models.CharField(default='USD', max_length=8)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de orçamento',
                'verbose_name_plural': 'Configuração de orçamento',
            },
        ),
        migrations.CreateModel(
            name='EventoOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bloqueio', 'Bloqueio')], default='bloqueio', max_length=16)),
                ('limite_atingido', models.CharField(blank=True, default='', max_length=16)),
                ('valor_solicitado', models.DecimalField(decimal_places=6, max_digits=14)),
                ('gasto_dia', models.DecimalField(decimal_places=6, max_digits=14)),
                ('gasto_mes', models.DecimalField(decimal_places=6, max_digits=14)),
                ('detalhe', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ReservaOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(blank=True, default='', max_length=64)),
                ('modelo', models.CharField(blank=True, default='', max_length=200)),
                ('valor_estimado', models.DecimalField(decimal_places=6, max_digits=14)),
                ('moeda', models.CharField(default='USD', max_length=8)),
                ('estado', models.CharField(choices=[('ativa', 'Ativa'), ('conciliada', 'Conciliada'), ('expirada', 'Expirada')], default='ativa', max_length=16)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('conciliada_em', models.DateTimeField(blank=True, null=True)),
                ('chamada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserva', to='ai.chamadaia')),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
    ]
