# Generated by Django 5.2.18 on 2026-10-09 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracao', '0002_auditoriaadministrativa'),
        ('content', '0002_conteudo_estado'),
        ('jobs', '0002_tarefa_interrupcao_solicitada'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='pipeline', max_length=64)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('em_execucao', 'Em execução'), ('concluida', 'Concluída'), ('falhou_parcial', 'Falhou (parcial)'), ('falhou', 'Falhou'), ('cancelada', 'Cancelada')], default='pendente', max_length=16)),
                ('secao', models.CharField(blank=True, default='', max_length=32)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('snapshot_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes', to='configuracao.snapshotconfiguracao')),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes', to='jobs.tarefa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default='', max_length=32)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('trecho', models.TextField(blank=True, default='')),
                ('verificado', models.BooleanField(default=False)),
                ('coletado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fonte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='sources.fonte')),
                ('registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='sources.registronormalizado')),
                ('versao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='content.versao')),
                ('execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='pipeline.execucao')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EtapaExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('saida', models.JSONField(blank=True, default=dict)),
                ('concluida_em', models.DateTimeField(auto_now_add=True)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='pipeline.execucao')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('execucao', 'nome'), name='uniq_etapa_execucao_nome')],
            },
        ),
    ]
