# Generated by Django 5.2.18 on 2026-10-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucao',
            name='motivo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
