# Generated by Django 5.2.18 on 2026-10-09 13:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarefa', models.CharField(max_length=64)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('intervalo_segundos', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('proxima_execucao', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['proxima_execucao'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pausado', models.BooleanField(default=False)),
                ('automatico', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do motor',
                'verbose_name_plural': 'Configuração do motor',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarefa', models.CharField(max_length=64)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('prioridade', models.IntegerField(default=0)),
                ('agendado_para', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('reservada', 'Reservada'), ('em_execucao', 'Em execução'), ('concluida', 'Concluída'), ('falhou', 'Falhou'), ('cancelada', 'Cancelada'), ('abandonada', 'Abandonada')], db_index=True, default='pendente', max_length=16)),
                ('origem', models.CharField(choices=[('automatico', 'Automático'), ('manual', 'Manual')], default='manual', max_length=16)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('limite_tentativas', models.PositiveIntegerField(default=3)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('worker', models.CharField(blank=True, default='', max_length=128)),
                ('reserva_token', models.CharField(blank=True, max_length=64, null=True)),
                ('lease_expira_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True, default='')),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('chave_idempotencia', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-prioridade', 'agendado_para', 'id'],
                'indexes': [models.Index(fields=['estado', 'agendado_para'], name='jobs_tarefa_estado_78183a_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('info', 'Info'), ('erro', 'Erro')], default='info', max_length=8)),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='jobs.tarefa')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
