# Generated by Django 5.2.18 on 2026-10-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='interrupcao_solicitada',
            field=models.BooleanField(default=False),
        ),
    ]
