# Generated by Django 5.2.18 on 2026-10-09 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_tarefa_interrupcao_solicitada'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(max_length=64)),
                ('modelo', models.CharField(max_length=200)),
                ('moeda', models.CharField(default='USD', max_length=8)),
                ('preco_entrada_por_milhao', models.DecimalField(decimal_places=6, max_digits=12)),
                ('preco_saida_por_milhao', models.DecimalField(decimal_places=6, max_digits=12)),
                ('vigente_de', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-vigente_de'],
                'constraints': [models.UniqueConstraint(fields=('provedor', 'modelo', 'vigente_de'), name='uniq_preco_provedor_modelo_vigencia')],
            },
        ),
        migrations.CreateModel(
            name='ChamadaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(max_length=64)),
                ('modelo', models.CharField(max_length=200)),
                ('finalidade', models.CharField(max_length=64)),
                ('etapa', models.CharField(blank=True, default='', max_length=64)),
                ('conteudo_id', models.IntegerField(blank=True, null=True)),
                ('correlacao', models.JSONField(blank=True, default=dict)),
                ('iniciada_em', models.DateTimeField()),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('duracao_ms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro'), ('timeout', 'Timeout'), ('incerto', 'Incerto')], db_index=True, max_length=16)),
                ('tentativa', models.PositiveIntegerField(default=1)),
                ('request_id_externo', models.CharField(blank=True, default='', max_length=200)),
                ('tokens_entrada', models.IntegerField(blank=True, null=True)),
                ('tokens_saida', models.IntegerField(blank=True, null=True)),
                ('tokens_cache', models.IntegerField(blank=True, null=True)),
                ('unidades_imagem', models.IntegerField(blank=True, null=True)),
                ('resolucao', models.CharField(blank=True, default='', max_length=32)),
                ('moeda', models.CharField(default='USD', max_length=8)),
                ('preco_aplicado', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('custo', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('origem_custo', models.CharField(choices=[('informado', 'Informado'), ('estimado', 'Estimado'), ('reconciliado', 'Reconciliado'), ('desconhecido', 'Desconhecido')], default='desconhecido', max_length=16)),
                ('erro', models.TextField(blank=True, default='')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamadas_ia', to='jobs.tarefa')),
            ],
            options={
                'ordering': ['-iniciada_em'],
                'indexes': [models.Index(fields=['finalidade', 'status'], name='ai_chamadai_finalid_89a4b5_idx')],
            },
        ),
    ]
