# Generated by Django 5.2.18 on 2026-10-09 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_tarefa_interrupcao_solicitada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=120, unique=True)),
                ('escopo', models.CharField(choices=[('sistema', 'Sistema'), ('geral', 'Geral'), ('secao', 'Seção'), ('agente', 'Agente')], max_length=16)),
                ('secao', models.CharField(blank=True, default='', max_length=64)),
                ('agente', models.CharField(blank=True, default='', max_length=64)),
                ('descricao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['escopo', 'chave'],
                'constraints': [models.UniqueConstraint(fields=('escopo', 'secao', 'agente'), name='uniq_config_escopo_alvo')],
            },
        ),
        migrations.CreateModel(
            name='SnapshotConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campos', models.JSONField(default=dict)),
                ('versoes', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_config', to='jobs.tarefa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='VersaoConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('campos', models.JSONField(default=dict)),
                ('ativa', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='configuracao.configuracao')),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-numero'],
                'constraints': [models.UniqueConstraint(fields=('configuracao', 'numero'), name='uniq_versao_config_numero')],
            },
        ),
    ]
