# Generated by Django 5.2.18 on 2026-10-09 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=64)),
                ('entidade', models.CharField(max_length=64)),
                ('entidade_id', models.CharField(max_length=64)),
                ('antes', models.JSONField(blank=True, null=True)),
                ('depois', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria administrativa',
                'verbose_name_plural': 'Auditoria administrativa',
                'ordering': ['-criado_em'],
            },
        ),
    ]
