# Generated by Django 5.2.18 on 2026-10-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0002_auditoriaadministrativa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditoriaAdministrativa',
        ),
    ]
